# cloudbuild.yaml
options:
  # create default logs bucket in the same region as builds
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

steps:
# 1) Build the image using the Docker cloud-builder
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA', '.']

# 2) Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA']

# (Later you will add a cloud-sdk step for deployment - step 9)
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA'
