options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA'
    ]



images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/rohit-101002678/:$COMMIT_SHA'
